server:
  port: ${PORT:8080}
  error:
    include-message: always
client:
  nominatim:
    baseUrl: https://nominatim.openstreetmap.org/search
    formatData: format=json
    limit: 1
  viacep:
    baseUrl: https://viacep.com.br/ws/%s/json/
security:
  secret: f14pS3cr37
  expireInSeconds: 300
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/bancoDeSangue?createDatabaseIfNotExist=true}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:123456}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true