CREATE DATABASE DOACAO_SANGUE;
USE DOACAO_SANGUE;

/*
CODPESSOA VARCHAR (3),
CPFCNPJ VARCHAR (14) NOT NULL,
NOME VARCHAR (100) NOT NULL,
DATANASCIMENTO DATE NOT NULL,
TIPOPESSOA CHAR (1) CHECK (TIPOPESSOA = 'F' OR TIPOPESSOA = 'J') NOT NULL,
TIPOSANGUINEO VACHAR (3) NOT NULL -- A+, B+, AB+, O+, A-, B-, AB-, O-
*/

CREATE TABLE ENDERECOS(
ID_END VARCHAR (3) NOT NULL, -- pensei em fazer com AUTO_INCREMENT
UNIDADE VARCHAR (100),
TIPOLOGRADOURO VARCHAR (7),-- rua, avenida, alameda, estrada, rodovia etc..
LOGRADOURO VARCHAR (100),-- nome do logradouro
NUMERO NUMERIC,-- numero logradouro
BAIRRO VARCHAR (100),
CIDADE VARCHAR (50),
UF VARCHAR (2),
CEP VARCHAR (9),
OBSERVACAO VARCHAR (100), -- detalhes do local onde esta a unidade
FUNCIONAMENTO VARCHAR(100), -- horario de funcionamento
CONSTRAINT PK_ENDERECO PRIMARY KEY (ID_END));


INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('001','Aclimação','Rua','Castro Alves',60,'Aclimação','São Paulo','SP','01532-000',' 4º andar','2ª a Sábado das 8:00/13:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('002','1 Bela Vista','Rua','Maestro Cardim',1041,'Bela Vista','São Paulo','SP','01323-001','4º andar – Bloco F','2ª a 6ª das 08:00/18:00h Sábado das 08:00/15:30h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('003','2 Bela Vista','Avenida','Paulista',200,'Bela Vista','São Paulo','SP','01310-000','','')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('004','3 Bela Vista','Rua','Dona Adma Jafet',91,'Bela Vista','São Paulo','SP','01532-000','3° Subsolo','Segunda a Sábado das 07:00 às 18:00 horas')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('005','4 Bela Vista','Rua','Dr. Seng',320,'Bela Vista','São Paulo','SP','01331-020','1 subsolo','2ª a 6ª das 08:00/11:30hs e Sábado das 08:00/12:00h e das 13:00 às 16:30hs')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('006','Campo Limpo','Estrada','Itapecerica',1661,'Vila Maracana','São Paulo','SP','05835-005','','2ª a Sábado das 8:00/13:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('007','1 Centro','Rua','Marques de Itu,',579,'Vila Buarque','São Paulo','SP','01223-001','','2ª a 6ª das 7:00/18:00h Sábado das 7:00/15:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('008','2 Centro','Avenida','Brigadeiro Luiz Antonio',683,'Bela Vista','São Paulo','SP','01317-000','','2ª a 6ª das 7:00/11:30hs')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('009','3 Centro','Rua','Dona Adma Jafe',91,'Bela Vista','São Paulo','SP','01532-000','','2ª a Sábado das 07:00 às 18:00 h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('010','Cerqueira César','Rua','Peixoto Gomide',613,'Jardim Paulista','São Paulo','SP','01409-001','1º subsolo','2ª a 6ª das 7:00/18:00h Sábados, feriados e emendas, das 8:00/17:00h 1º e 3º domingos de cada mês, das 8:00/13:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('011','2 Cerqueira César','Avenida','Dr. Enéas Carvalho de Aguiar,',155,'Cerqueira César','São Paulo','SP','05403-000','1º andar','2ª a 6ª das 7h/18h Sábados, feriados e emendas de feriados das 8h/17h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('012','Ermelino Matarazzo','Alameda','Rodrigo de Brum',1989,'Ermelino Matarazzo','São Paulo','SP','03807-230','','2ª a Sábado das 8h/13h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('013','','Avenida','Dante Pazzanes',500,'Vila Mariana','São Paulo','SP','04012-180','','2ª, 3ª, 5ª e 6ª das 8h/13h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('014','Itaquera','Rua','Harry Danemberg',473,'Vila Carmosina','São Paulo','SP','08270-010','','2ª a 6ª das 7h/16h – Sábado das 7h/12h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('015','Jacanã','Rua','Michel Ouchana',94,'Jaçanã','São Paulo','SP','02276-140','','2ª a 6ª das 7:00/15h30 Sábado das 7:00/11h30')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('016','1 Liberdade','Rua','Professor Antonio Prudente',211,'Liberdade','São Paulo','SP','01532-000','','2ª a Sábado das 8h/17h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('017','2 Liberdade','Rua','Barão de Iguape',212,'Liberdade','São Paulo','SP','01507-000','2º andar','2ª a 6ª das 8:00/17:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('018','Mandaqui','Rua','Voluntários da Pátria',4227,'Mandaqui','São Paulo','SP','02401-400','','2ª a 6ª das 8:00/16h30')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('019','Morumbi','Avenida','Albert Einstein',627,'Morumbi','São Paulo','SP','05652-900','4º andar, Bloco A','2ª a 6ª das 8:00/21h Sábado das 8:00/17h Domingos: Consulte site ou telefone')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('020','Paraíso','Rua','Abilio Soares',176,'Paraíso','São Paulo','SP','04005-000','','2ª a 6ª das 8:00/17h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('021','Pompéia','Rua','Taváres Bastos',425,'Pompeia','São Paulo','SP','05012-020','','2ª a 6ª das 8:00/18:00h – Sábado das 8:00/16:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('022','Santa Cecília','Rua','Rua Conselheiro Brotero',1486,'Higienópolis','São Paulo','SP','01232-010','Térreo','2ª a 6ª das 8:00/14:00h Sábado das 8:00/13:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('023','Santana','Rua','Voluntários da Pátria',3997,'Santana','São Paulo','SP','02401-300','','2ª a Sábado das 8:00/12:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('024','Santo Amaro','Rua','Iguatinga',382,'Santo Amaro','São Paulo','SP','04744-040','','2ª a Sábado das 8:00/16:40hs')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('025','Tatuapé','Avenida','Celso Garcia',4815,'Tatuapé','São Paulo','SP','03063-000','','2ª a Sábado das 8:00/13:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('026','Vila Campo Grande','Rua','João Francisco de Moura',251,'Vila Campo Grande','São Paulo','SP','04455-170','','2ª a 6ª das 7h30 às 12h30 e sábado, 1º, 3º e 5º de cada mês, das 7h30 às 16h30')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('027','1 Vila Clementino','Rua','Dr. Diogo de Faria',824,'Vila Clementino','São Paulo','SP','04037-002','','2ª a 6ª das 8:00/17:30h  Sábado das 8:00/13:00hs')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('028','2 Vila Clementino','Rua','Borges Lagoa',1450,'Vila Clementino','São Paulo','SP','04038-004','','2ª a Sábado das 8:00/17:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('029','3 Vila Clementino','Rua','Pedro de Toledo',1800,'Vila Clementino','São Paulo','SP','04039-000','','2ª a 6ª das 7:30/17:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('030','Vila Mariana','Rua','Madre Cabrine',462,'Vila Mariana','São Paulo','SP','04020-001','2º andar, Bloco D','2ª a 6ª das 8:00/16:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('031','Vila Nova Conceição','Rua','Dr. Alceu de Campos Rodrigues',46,'Vila Nova Conceição','São Paulo','SP','04544-000','14º andar','2ª a Sábado das 8:00/16:40hs')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('032','Vila Olímpia','Avenida','Santo Amaro',2468,'Brooklin','São Paulo','SP','04556-100','','2ª a 6ª das 8:00/17:00h')



-- Postos de coleta de sangue na Grande São Paulo


INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('033','Barueri','Rua','Angela Mirella',354,'Jardim Barueri','Barueri','SP','06411-330','','2ª a 6ª das 8:00/16:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('034','Diadema','Rua','José Bonifacio',1641,'Serraria','Diadema','SP','09980-150','com intervalo para almoço','2ª a 6ª das 7:00/15:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('035','1 Guarulhos','Rua','Santo Antônio',95,'Jardim Sao Paulo','Guarulhos','SP','07110-150','','2ª a 6ª das 8:00/17:00h – Sábados 8:00/13:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('036','2 Guarulhos','Rua','Maria Cândida Pereira ',568,'Vila Sao Joao','Guarulhos','SP','07041-020','','2ª a 6ª das 8:00/16:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('037','Osasco','Rua','Ari Barros',355,'Presidente Altino','Osasco','SP','06216-240','','2ª a 6ª das 8:00/16h30 – Sábados 8:00/16:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('038','1 Santo André','Rua','Dr.Henrique Calderazzo',321,'Paraíso','Santo André','SP','09190-615','','2ª a Sábado das 8:00/13:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('039','2 Santo André','Avenida','João Ramalho',326,'Centro','Santo André','SP','09030-320','','2ª a Sábado das 8:00/13:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('040','São Bernardo do Campo','Rua','Pedro Jacobucci',440,'Jardim das Americas','São Bernardo do Campo','SP','09725-750','','2ª a Sábado das 8:00/13:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('041','São Caetano do Sul','Rua','Peri,',361,'Osvaldo Cru','São Caetano do Sul','SP','09540-290','','2ª a Sábado das 8:00/12:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('042','Suzano','Avenida','Antonio Marques Figueira',1861,'Vila Figueira','Suzano','SP','08676-165','','2ª a 6ª das 8:00/14:00h')



-- Postos de coleta de sangue no interior


INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('043','Ourinhos','Rua','Joaquim de Azevedo',770,'Vila Moraes','Ourinhos','SP','19900-280','','2ª a 6ª das 7:00/18:30hs Sábados das 7:00/12:30 hs')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('044','Ribeirão Preto','Rua','Quintino Bocaiuva',895,'Centro','Ribeirão Preto','SP','14020-095','','2ª, 4ª e 6ª das 7:00/14:00h – 3ª e  5ª das 7:00/17:00h Sábado das 7:00/12:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('045','Tatuí','Rua','Maneco Pereira',299,'Quatrocentos','Tatuí','SP','18270-400','','2ª a 6ª das 7:00/9:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('046','São José do Rio Preto','Rua','Luiz  Vaz de Camões',3236,'Redentora','São José do Rio Preto','SP','15015-750','Prédio de Vidro – Sub-solo1','2ª a 6ª das 8:00/17:30h Sábados, domingos e feriados das 7:00/12:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('047','1 Jundiaí','Rua','Senador Fonseca',1314,'Centro','Jundiaí','SP','13201-017','','2ª a 6ª das 7:00/11:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('048','1 Santos','Rua','Pedro Américo',60,'Campo Grande','Santos','SP','11075-400','','2ª a 6ª das 8:00/14:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('049','1 Bauru','Avenida','Engenheiro Luis Edmundo Carrijo Coube',100,'Jardim Marabá','Bauru','SP','','Coleta somente Plaquetas por Aférese. Agendar atendimento','Coleta somente Plaquetas por Aférese. Agendar atendimento.')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('050','Americana','Avenida','da Saúde,',415,'Jardim Nossa Senhora de Fátima','Americana','SP','13478-640','','2ª a 6ª das 8:00/11:30hs')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('051','Presidente Prudente','Rua','Joaquim',1297,'Jardim Colina','Presidente Prudente','SP','19050-680','','2ª a domingo das 7:00/17:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('052','1 Campinas','Rua','Onze de Agosto',415,'Centro','Campinas','SP','13013-101','','2ª a 6ª das 7:30/12:30hs  Sábados das 8:00/12:00hs')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('053','2 Jundiaí','Rua','XV de Novembro',1848,'Vila Municipal','Jundiaí','SP','13201-305','','2ª a Sábado das 7:30/12h30hs')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('054','Sorocaba','Rua','Comendador Pereira Inácio',564,'Lajeado','Sorocaba','SP','18030-005','','2ª a Sábado das 7:30/12:30hs')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('055','2 Campinas','Rua','Irmã Serafina',259,'Centro','Campinas','SP','13015-201','','2ª a 6ª das 8:00/11:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('056','Botucatu','Avenida','Prof. Montenegro',0,'Distrito de Rubião Júnior','Botucatu','SP','18618-687','','2ª a 6ª das 7:30/16:30hs Sábado das 7:00/13:00')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('057','Assis','Praça','Dr Symphronio Alves dos Santos',0,'Centro','Assis','SP','19814-015','','2ª a Sábado das 7:00/12:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('058','Adamantina','Rua','Joaquim Luiz Via',209,'Vila Cicma','Adamantina','SP','17800-000','','2ª a 6ª das 7:00/11:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('059','2 Bauru','Rua','Monsenhor Claro',8,'Centro','Bauru','SP','17015-130','','2ª a 6ª das 7:00/11:30hs e das 14:00/16:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('060','Marília','Rua','Lourival Freire',240,'Bairro Fragata','Marília','SP','17519-050','','2ª a 6ªfeira das 7:00/18:00h e as 5ª das 7:00/20:00hs Sádados das 7:00/12:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('061','São José dos Campos','Rua','Antonio Saes',425,'Centro','São José dos Campos','SP','12210-040','','2ª a 6ª das 7:00/12:30hs')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('062','Ribeirão Preto','Rua','Quintino Bocaiúva',770,'Centro','Ribeirão Preto','SP','14015-160','','2ª a 6ª 7:00/17:00h Sábados e domingos 7:00/11:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('063','Tupã','Rua','Manoel Ferreira Damião',426,'Varpa','Tupã','SP','17601-901','','2ª a 6ª das 7:30/12:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('064','São Vicente','Rua','Frei Gaspar',790,'Centro','São Vicente','SP','11310-061','','2ª a 6ª das 8:00/12:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('065','São Carlos','Rua','Paulino botelho de Abreu Sampaio',573,'Vila Pureza','São Carlos','SP','13561-060','','2ª a Sábado das 7:30/12:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('066','2 Santos','Avenida','Doutor Luiz da Costa',50,'Jabaquara','Santos','SP','11075-101','','2ª a 6ª das 7:00/17:00h Sábados das 7:00/11:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('067','Mogi das Cruzes','Rua','Rua Barão de Jacegua',1148,'Centro','Mogi das Cruzes','SP','08780-100','','2ª a 6ª das 07:30/12:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('068','Lins','Rua','Rua Nove de Julho',0,'Vila Buarque','Vila Moraes','Lins','SP','01221-010','s/n atrás da Santa Casa','2ª à 6ª das 8:00/12:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('069','Limeira','Avenida','Antonio Ometto',675,'Vila Claudia','Limeira','SP','13480-470','','2ª a 6ª das 7:00/14:00h Sábados das 7:00/11:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('070','Cubatão','Avenida','Henry Borden ',0,'Vila Santa Rosa','Cubatão','SP','','2ª a 6ª das 7:00/14:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('071','São José dos Campos','Rua','Santa Clara,',450,'Vila Adyanna','São José dos Campos','SP','12243-630','',' 	2ª a 6ª das 8:00/11:45hs')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('072','Jaú','Rua','Dona Silvéria',150,'Centro','Jaú','SP','17210-070','','2ª, 3ª, 5ª e 6ª das 7:30/16:30hs e 4ª das 7:30/20:00h Sábado das 7:30/12:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('073','3 Santos','Rua','Oswaldo Cruz',197,'Boqueirão','Santos','SP','','','2ª a 6ª feira das 7:00/17:00h Último sábado do mês das 8:00/12:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('074','2 Presidente Prudente','Rua','Wenceslau Braz',05,'Vila Euclides','Presidente Prudente','SP','19014-030','','2ª, 3ª ,4ª e 6ª das 7:00/17:00h 5ª das 7:00/19:00h Sábados das 7:00/12:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('075','3 Bauru','Rua','Rua: Monsenhor Claro',8,'Centro','Bauru','SP','17800-000','','2ª a 6ª das 7:00/11:30hs e das 14:00/16:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('076','Barretos','Rua','Antenor Duarte Vilella',1331,'Bairro Dr. Paulo Prata','Barretos','SP','14784-400','','2ª a 6ª das 7:00/12:00hs Sábados e domingos das 7:00/11:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('077','Araraquara','Rua','Expedicionários do Brasil',1621,'Centro','Araraquara','SP','14801-360','','2ª a 6ª das 7:00 às 18:00h Sábado das 8:00 às12:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('078','Campinas','Rua','Carlos Chagas',480,'Cidade Universitaria','Campinas','SP','13083-878','','2ª a sábado, inclusive feriados das 7h30/15h00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('079','Campinas','Avenida','Prefeito Faria Lima,',340,' Parque Itália','Campinas','SP','13036-220','','2ª a sábado das 8:00/14h00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('080','Campinas','Avenida','John Boyd Dunlop',0,'Jardim Ipaussurama','Campinas','SP','19900-280','s/n','2ª a 6ª 8:00/14:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('081','Sumaré','Avenida','da Amizade',2400,'Jardim Bela Vista','Sumaré','SP','13175-490','','2ª a 6ª 8:00/12:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('082','Campinas','Rua','Dr. Gabriel Porto',1270,'Cidade Universitária','Campinas','SP','13083-210','','2ª a 6ª 8:00/12:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('083','Piracicaba','Avenida','Independência',953,'Alto','Piracicaba','SP','13419-155','','2ª a 6ª 7:30/13:30h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('084','Taubaté','Rua','Joaquim Távora',0,'Centro','Taubaté','SP','19900-280','s/n','2ª a 6ª 7:30/15:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('085','São José do Rio Preto','Rua','amil Feres Kfuri',80,'Jd. Panorama','São José do Rio Preto','SP','15091-240','','2ª a domingo das 7:00/13:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('086','Catanduva','Rua','13 de Maio',974,'Centro','Catanduva','SP','15800-010','','4ª a domingo das 7:00/13:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('087','Ribeirão Preto','Rua','Tenente Catão Roxo',2501,'Monte alegre','Ribeirão Preto','SP','14051-140','','2ª a domingo das 7:00/13:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('088','Ribeirão Preto','Rua','Quintino Bocaiúva',470,'Centro','Ribeirão Preto','SP','14015-160','','2ª a 6ª das 7:00/19:00h Domingos e feriados das 7:00/13:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('089','Serrana','Rua','Nossa Senhora Dores',741,'Centro','Serrana','SP','14150-000','','2ª a sábado das 7:00/12:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('090','Batatais','Rua','Dr. Manoel Furtado',235,'Centro','Batatais','SP','14300-029','','2ª a 5ª das 7:00/12:00h – 6ª das 7:00/11:00h e segundo sábado do mês das 7:00/11:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('091','Olímpia','Rua','Síria',190,'Centro','Olímpia','SP','15400-000','','3ª a sábado das 7:00/12:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('092','Bebedouro','Avenida','Raul Furquim',2010,'Jd. Júlia','Bebedouro','SP','14706-045','','3ª a sábado das 7:00/12:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('093','Araçatuba','Avenida','Arthur Ferreira da Costa',330,'Aviação','Araçatuba','SP','16055-605','','2ª das 8:00/19:00h, 3ª a 6ª das 8:00/17:00h Sábados das 7:00/12:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('094','Presidente Prudente','Rua','Wenceslau Braz',05,'Vila Euclides','Presidente Prudente','SP','19014-030','','2ª, 3ª, 4ª e 6ª das 7:00/17:00h e 5ª das 7:00/19:00h Sábado das 7:00/12:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('095','Franca','Avenida','Dr. Hélio Palermo',4181,'Recanto do Itambé','Franca','SP','14409-045','','2ª das 7:00/19:00h, 3ª a 6ª das 7:00/17:00h Sábado das 7:00/12:00h')

INSERT INTO ENDERECOS (ID_END,UNIDADE,TIPOLOGRADOURO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,CEP,OBSERVACAO,FUNCIONAMENTO)
			   VALUES ('096','Fernandópolis','Rua','Simão dos Santos Gomes',266,'Jardim Santista','Fernandópolis','SP','15600-000','','2ª a 6ª das 7:30/18:30hs Sábado das 8:00/12:00h')


